apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: recall-configuration
  namespace: recall
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://recall-zipkin:9411/api/v2/spans"